In [9]:
import csv
with open("source-code/2_pandas_basics_code/movies.csv","r") as f:
    data=list(csv.reader(f))
    header= data[0]
    data=data[1:]

def calculate_movies_stats(data,industry=None):
    ratings=[]
    for row in data:
        if row[3]!='NULL' and (not industry or row[1]==industry):
            ratings.append(float(row[3]))
    mx_rating= max(ratings)
    min_rating= min(ratings)
    avr_rating=sum(ratings)/len(ratings)
    return mx_rating,min_rating,avr_rating
max_rat,min_rat,avr_rat = calculate_movies_stats(data)
print(f"max_ratings is : {max_rat}, min_rating is : {min_rat}, average_rating is : {avr_rat}")

max_rat,min_rat,avr_rat = calculate_movies_stats(data,industry="Bollywood")
print(f"Bollywood max_ratings is : {max_rat}, min_rating is : {min_rat}, average_rating is : {avr_rat}")

max_rat,min_rat,avr_rat = calculate_movies_stats(data, industry="Hollywood")
print(f" Hollywood max_ratings is : {max_rat}, min_rating is : {min_rat}, average_rating is : {avr_rat}")

max_ratings is : 9.3, min_rating is : 1.9, average_rating is : 7.919444444444445
Bollywood max_ratings is : 8.4, min_rating is : 1.9, average_rating is : 7.656250000000001
 Hollywood max_ratings is : 9.3, min_rating is : 6.8, average_rating is : 8.130000000000003

In [11]:
import pandas as pd

df=pd.read_csv("movies.csv")
df

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.00,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.00,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.00,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.00,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.00,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.00,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.00,701.8,Millions,USD,English
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.00,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.00,460.5,Millions,USD,English
9,Titanic,Hollywood,1997,7.9,Paramount Pictures,200.00,2202.0,Millions,USD,English
10,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,3.18,3.3,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.00,2847.0,Millions,USD,English
12,The Godfather,Hollywood,1972,9.2,Paramount Pictures,7.20,291.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.00,1006.0,Millions,USD,English
14,Schindler's List,Hollywood,1993,9.0,Universal Pictures,22.00,322.2,Millions,USD,English
15,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,63.00,1046.0,Millions,USD,English
16,Parasite,Hollywood,2019,8.5,NaN,15.50,263.1,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.00,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.00,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.70,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.00,714.4,Millions,USD,English
21,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,400.00,2000.0,Millions,INR,Hindi
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.00,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.00,1360.0,Millions,INR,Hindi
24,Bajirao Mastani,Bollywood,2015,7.2,NaN,1.40,3.5,Billions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.00,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.00,410.0,Millions,INR,Hindi
27,PK,Bollywood,2014,8.1,Vinod Chopra Films,850.00,8540.0,Millions,INR,Hindi
28,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1.00,5.9,Billions,INR,Hindi
29,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,250.00,3409.0,Millions,INR,Hindi
30,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,900.00,11690.0,Millions,INR,Hindi
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.80,3.1,Billions,INR,Hindi
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.00,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.00,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.00,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.50,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.80,6.5,Billions,INR,Telugu

In [12]:
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English

In [13]:
df.tail()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
32,Shershaah,Bollywood,2021,8.4,Dharma Productions,500.0,950.0,Millions,INR,Hindi
33,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,1.0,12.5,Billions,INR,Kannada
34,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2.0,3.6,Billions,INR,Telugu
35,RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu
36,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,1.8,6.5,Billions,INR,Telugu

In [14]:
df.sample()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English

In [15]:
df[2:7]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
6,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,English

In [17]:
df.shape

(37, 10)

In [19]:
print(type(df))
type(df.imdb_rating)

<class 'pandas.core.frame.DataFrame'>

pandas.core.series.Series

In [21]:
## Properties and methods
df.imdb_rating.max(), df.imdb_rating.min(), df.imdb_rating.mean()

(9.3, 1.9, 7.919444444444445)

In [23]:
df_b=df[df.industry=="Bollywood"]
df_h=df[df.industry=="Hollywood"]

In [24]:
df.imdb_rating.max(), df.imdb_rating.min(), df.imdb_rating.mean()

(9.3, 1.9, 7.919444444444445)

In [26]:
df_b.imdb_rating.max(), df_b.imdb_rating.min(), df_b.imdb_rating.mean()

(8.4, 1.9, 7.656250000000001)

In [27]:
df_h.imdb_rating.max(), df_h.imdb_rating.min(), df_h.imdb_rating.mean()

(9.3, 6.8, 8.130000000000003)

## 9.2 Dataframes Basics

In [28]:
import pandas as pd

In [29]:
df=pd.read_csv("movies.csv")

In [32]:
print(df.industry.unique())
df['industry'].unique()               ## we can use both way to access and specify our conditions

['Bollywood' 'Hollywood']

array(['Bollywood', 'Hollywood'], dtype=object)

In [33]:
df['language'].unique()

array(['Bengali', 'English', 'Hindi', 'Kannada', 'Telugu'], dtype=object)

In [35]:
print(df.language.value_counts())
df['language'].value_counts()

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

language
English    20
Hindi      12
Telugu      3
Bengali     1
Kannada     1
Name: count, dtype: int64

In [36]:
## accessing and filtering columns
df_new=df[['title','imdb_rating','industry']]
df_new

                                          title  imdb_rating   industry
0                               Pather Panchali          8.3  Bollywood
1   Doctor Strange in the Multiverse of Madness          7.0  Hollywood
2                         Thor: The Dark World           6.8  Hollywood
3                               Thor: Ragnarok           7.9  Hollywood
4                       Thor: Love and Thunder           6.8  Hollywood
5                      The Shawshank Redemption          9.3  Hollywood
6                                  Interstellar          8.6  Hollywood
7                      The Pursuit of Happyness          8.0  Hollywood
8                                     Gladiator          8.5  Hollywood
9                                       Titanic          7.9  Hollywood
10                        It's a Wonderful Life          8.6  Hollywood
11                                       Avatar          7.8  Hollywood
12                                The Godfather          9.2  Hollywood
13                              The Dark Knight          9.0  Hollywood
14                             Schindler's List          9.0  Hollywood
15                                Jurassic Park          8.2  Hollywood
16                                     Parasite          8.5  Hollywood
17                            Avengers: Endgame          8.4  Hollywood
18                       Avengers: Infinity War          8.4  Hollywood
19           Captain America: The First Avenger          6.9  Hollywood
20          Captain America: The Winter Soldier          7.8  Hollywood
21                  Dilwale Dulhania Le Jayenge          8.0  Bollywood
22                                     3 Idiots          8.4  Bollywood
23                     Kabhi Khushi Kabhie Gham          7.4  Bollywood
24                             Bajirao Mastani           7.2  Bollywood
25                             Taare Zameen Par          8.3  Bollywood
26                          Munna Bhai M.B.B.S.          8.1  Bollywood
27                                           PK          8.1  Bollywood
28                                        Sanju          NaN  Bollywood
29                            The Kashmir Files          8.3  Bollywood
30                            Bajrangi Bhaijaan          8.1  Bollywood
31                                       Race 3          1.9  Bollywood
32                                    Shershaah          8.4  Bollywood
33                             K.G.F: Chapter 2          8.4  Bollywood
34                    Pushpa: The Rise - Part 1          7.6  Bollywood
35                                          RRR          8.0  Bollywood
36                     Baahubali: The Beginning          8.0  Bollywood

In [41]:
## Filtering rows
print(df[(df['release_year']>=2000) & (df['release_year']<=2010)])
df[(df.release_year>=2000) & (df.release_year<=2010)]

                       title   industry  release_year  imdb_rating  \
7   The Pursuit of Happyness  Hollywood          2006          8.0
8                  Gladiator  Hollywood          2000          8.5
11                    Avatar  Hollywood          2009          7.8
13           The Dark Knight  Hollywood          2008          9.0
22                  3 Idiots  Bollywood          2009          8.4
23  Kabhi Khushi Kabhie Gham  Bollywood          2001          7.4
25          Taare Zameen Par  Bollywood          2007          8.3
26       Munna Bhai M.B.B.S.  Bollywood          2003          8.1

                      studio  budget  revenue      unit currency language
7          Columbia Pictures    55.0    307.1  Millions      USD  English
8       Universal Pictures     103.0    460.5  Millions      USD  English
11          20th Century Fox   237.0   2847.0  Millions      USD  English
13                   Syncopy   185.0   1006.0  Millions      USD  English
22        Vinod Chopra Films   550.0   4000.0  Millions      INR    Hindi
23        Dharma Productions   390.0   1360.0  Millions      INR    Hindi
25                       NaN   120.0   1350.0  Millions      INR    Hindi
26  Vinod Chopra Productions   100.0    410.0  Millions      INR    Hindi

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
7,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English
8,Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English
11,Avatar,Hollywood,2009,7.8,20th Century Fox,237.0,2847.0,Millions,USD,English
13,The Dark Knight,Hollywood,2008,9.0,Syncopy,185.0,1006.0,Millions,USD,English
22,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,550.0,4000.0,Millions,INR,Hindi
23,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,390.0,1360.0,Millions,INR,Hindi
25,Taare Zameen Par,Bollywood,2007,8.3,NaN,120.0,1350.0,Millions,INR,Hindi
26,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,100.0,410.0,Millions,INR,Hindi

In [43]:
df[df.studio=="Marvel Studios"]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English
17,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,400.0,2798.0,Millions,USD,English
18,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,400.0,2048.0,Millions,USD,English
19,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,216.7,370.6,Millions,USD,English
20,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,177.0,714.4,Millions,USD,English

In [44]:
df.describe()

       release_year  imdb_rating        budget        revenue
count     37.000000    36.000000     37.000000      37.000000
mean    2007.027027     7.919444   2084.975135    4117.135135
std       17.657995     1.204947  11477.487145   16372.462682
min     1946.000000     1.900000      1.000000       3.100000
25%     2001.000000     7.800000     15.500000     263.100000
50%     2014.000000     8.100000    165.000000     701.800000
75%     2018.000000     8.400000    250.000000    2000.000000
max     2022.000000     9.300000  70000.000000  100000.000000

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         37 non-null     object
 1   industry      37 non-null     object
 2   release_year  37 non-null     int64
 3   imdb_rating   36 non-null     float64
 4   studio        34 non-null     object
 5   budget        37 non-null     float64
 6   revenue       37 non-null     float64
 7   unit          37 non-null     object
 8   currency      37 non-null     object
 9   language      37 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 3.0+ KB

In [46]:
df.imdb_rating.max()

9.3

In [48]:
df[(df.imdb_rating == df.imdb_rating.max()) | (df.imdb_rating == df.imdb_rating.min())]

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language
5,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English
31,Race 3,Bollywood,2018,1.9,Salman Khan Films,1.8,3.1,Billions,INR,Hindi

In [53]:
## Adding a new column
print(df.head(1))
df["age"]=df.release_year.apply(lambda x:2025-x)  ## > df["release_year"].apply(lambda x: 2025 - x)  ,,both way are same
df.head()

             title   industry  release_year  imdb_rating  \
0  Pather Panchali  Bollywood          1955          8.3

                      studio   budget   revenue       unit currency language  \
0  Government of West Bengal  70000.0  100000.0  Thousands      INR  Bengali

   age
0   70

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,3
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,3

In [54]:
df["Profit"]=df.apply(lambda x: x["revenue"] - x["budget"],axis=1)
df.head()

,title,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,Profit
0,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70,30000.0
1,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,3,754.8
2,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12,479.8
3,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8,674.0
4,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,3,420.0

In [ ]:
## set and reset index and using loc[] and iloc[]

In [68]:
df.set_index("title",inplace=True)  ## we use inplace = True , to modified our original dataframe
df.head()

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,Profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70,30000.0
Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,200.0,954.8,Millions,USD,English,3,754.8
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,3,420.0

In [60]:
df.index

Index(['Pather Panchali', 'Doctor Strange in the Multiverse of Madness',
       'Thor: The Dark World ', 'Thor: Ragnarok ', 'Thor: Love and Thunder ',
       'The Shawshank Redemption', 'Interstellar', 'The Pursuit of Happyness',
       'Gladiator', 'Titanic', 'It's a Wonderful Life', 'Avatar',
       'The Godfather', 'The Dark Knight', 'Schindler's List', 'Jurassic Park',
       'Parasite', 'Avengers: Endgame', 'Avengers: Infinity War',
       'Captain America: The First Avenger',
       'Captain America: The Winter Soldier', 'Dilwale Dulhania Le Jayenge',
       '3 Idiots', 'Kabhi Khushi Kabhie Gham', 'Bajirao Mastani ',
       'Taare Zameen Par', 'Munna Bhai M.B.B.S.', 'PK', 'Sanju',
       'The Kashmir Files', 'Bajrangi Bhaijaan', 'Race 3', 'Shershaah',
       'K.G.F: Chapter 2', 'Pushpa: The Rise - Part 1', 'RRR',
       'Baahubali: The Beginning'],
      dtype='object', name='title')

In [62]:
df.loc["Pather Panchali"]

industry                        Bollywood
release_year                         1955
imdb_rating                           8.3
studio          Government of West Bengal
budget                            70000.0
revenue                          100000.0
unit                            Thousands
currency                              INR
language                          Bengali
age                                    70
Profit                            30000.0
Name: Pather Panchali, dtype: object

In [63]:
df.loc[["Pather Panchali","PK","RRR"]]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,Profit
title,,,,,,,,,,,
Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,70000.0,100000.0,Thousands,INR,Bengali,70,30000.0
PK,Bollywood,2014,8.1,Vinod Chopra Films,850.0,8540.0,Millions,INR,Hindi,11,7690.0
RRR,Bollywood,2022,8.0,DVV Entertainment,5.5,12.0,Billions,INR,Telugu,3,6.5

In [66]:
df.iloc[2:10]

,industry,release_year,imdb_rating,studio,budget,revenue,unit,currency,language,age,Profit
title,,,,,,,,,,,
Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,165.0,644.8,Millions,USD,English,12,479.8
Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,180.0,854.0,Millions,USD,English,8,674.0
Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,250.0,670.0,Millions,USD,English,3,420.0
The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,25.0,73.3,Millions,USD,English,31,48.3
Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,165.0,701.8,Millions,USD,English,11,536.8
The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,55.0,307.1,Millions,USD,English,19,252.1
Gladiator,Hollywood,2000,8.5,Universal Pictures,103.0,460.5,Millions,USD,English,25,357.5
Titanic,Hollywood,1997,7.9,Paramount Pictures,200.0,2202.0,Millions,USD,English,28,2002.0

In [69]:
df.reset_index(inplace=True)

## Read, Write Excel and CSV files

In [71]:
df=pd.read_csv("stock_data.csv")
df

,Datasource: Google finance,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,tickers,eps,revenue,price,people
1,GOOGL,27.82,87,845,larry page
2,WMT,4.61,484,65,n.a.
3,MSFT,-1,85,64,bill gates
4,RIL,not available,50,1023,mukesh ambani
5,TATA,5.6,-1,n.a.,ratan tata

In [74]:
df=pd.read_csv("stock_data.csv", header=1)   ## skiping 0th row and making 1st header
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [76]:
## specifying column names
df=pd.read_csv("stock_data.csv",header =1, names=["Stock_symbol","eps", "revenue","price","people"])
df

  Stock_symbol            eps  revenue price         people
0        GOOGL          27.82       87   845     larry page
1          WMT           4.61      484    65           n.a.
2         MSFT             -1       85    64     bill gates
3         RIL   not available       50  1023  mukesh ambani
4         TATA            5.6       -1  n.a.     ratan tata

In [77]:
## filtering our data to our required no. of rows 
df=pd.read_csv("stock_data.csv",header=1,nrows=2)   ## nrows=
df

  tickers    eps  revenue  price      people
0   GOOGL  27.82       87    845  larry page
1     WMT   4.61      484     65        n.a.

In [86]:
## adding NaN value to wrong entries
df=pd.read_csv("stock_data.csv",header=1,na_values={
    'eps':[-1,'not available'],
    'revenue':[-1],
    'people':['n.a.'],
    'price' :['n.a.']
})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [84]:
## we can also directly specify entries without using dict of key and values,    but it is not much efficient as it will traverse each entries
df=pd.read_csv('stock_data.csv',header=1, na_values=['n.a.'])
df

  tickers            eps  revenue   price         people
0   GOOGL          27.82       87   845.0     larry page
1     WMT           4.61      484    65.0            NaN
2    MSFT             -1       85    64.0     bill gates
3    RIL   not available       50  1023.0  mukesh ambani
4    TATA            5.6       -1     NaN     ratan tata

In [87]:
## exporting or saving a csv file to directory
df["pe"]= df['price']/df['eps']

df.to_csv('pe1.csv', index=False)  ## index=False , meanse removing index column from csv file

In [88]:
## Reading excel files

In [90]:
pd_movies=pd.read_excel("movies_db.xlsx" ,"movies")
pd_movies.head(2)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5

In [94]:
pd_financials=pd.read_excel("movies_db.xlsx" ,"financials")
pd_financials.head(5)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions       $$
3       104   180.0    854.0  Millions  Dollars
4       105   250.0    670.0  Millions      USD

In [98]:
def curr_converter(currency):
    if currency =="$$" or currency =="Dollars":
        return "USD"
    return currency
pd_financials=pd.read_excel("movies_db.xlsx" ,"financials",converters={
    "currency":curr_converter
})
pd_financials.head(5)

   movie_id  budget  revenue      unit currency
0       101     1.0     12.5  Billions      INR
1       102   200.0    954.8  Millions      USD
2       103   165.0    644.8  Millions      USD
3       104   180.0    854.0  Millions      USD
4       105   250.0    670.0  Millions      USD

In [99]:
## merging these two df
df_merged=pd.merge(pd_movies,pd_financials, on ="movie_id")
df_merged.head(3)

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.0,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.0,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.0,644.8,Millions,USD

In [100]:
## saving it to the directory
df_merged.to_excel("moovies_merged.xlsx", sheet_name="merged", index=False)

In [102]:
## Creating a new df and then exporting it to excel file with sheet
df_weather=pd.DataFrame({
    'day':['1','2','3'],
    'tem':[28,32,38],
    'event':['Hot','Sunny','Cloudy']
})
df_weather

  day  tem   event
0   1   28     Hot
1   2   32   Sunny
2   3   38  Cloudy

In [103]:
with pd.ExcelWriter('weather.xlsx') as writer:
    df_weather.to_excel(writer,sheet_name="weather")